Repository ErikSchierboom/v3, pull requests merged in 2020-12, with the labels that each got.

#14 Update README.md!
  README.md
Labels: CI, bug

#16 Update README.md
  README.md
Labels: bug, reputation/contributed_code/major

#23 Update README.md
  README.md
Labels: reputation/contributed_code/minor
